[Interface]
PrivateKey = 0Nme7BX8uGWz08gglv8byoCnV6SMMJL6nQeLZ6aJIFo=
ListenPort = 51820
Address = 192.168.100.4/32

[Peer]
PublicKey = Q4GOuKHCMf/oNKydYvgBO+hxa7FJ2M6TN69Tnq9zplc=
AllowedIPs = 0.0.0.0/0
Endpoint = 45.114.60.26:51820
