[Interface]
Address = 192.168.100.1
PrivateKey = ABRVEr7ea9vSzKtU6+3b1cgfP7u4rOm2A68Um/Cc4nk=
ListenPort = 51820
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE

[Peer]
PublicKey = xSELf8R4rhx5zDVWdxRB9k6vYy+m1wwtISsVcL9UGyM=
AllowedIPs = 192.168.100.3/24
